language: python

python:
  - "2.7"

branches:
  only:
    - test

before_install:
  - "sudo apt-get install xvfb"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  

# command to install dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - python manage.py runserver 127.0.0.1:8000 &

# command to run tests
script: behave


