language: python

python:
  - "2.7"

branches:
  only:
    - test

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: behave

addons:
  sauce_connect:
    username: "hamiltonetsii"
    access_key: "ed01da28-a815-4e5f-abb2-535e7178d6ec"
